### ISSUE TITLE
Custom Trait in Model throws Exception

### ISSUE THREAD

**Issue by popovserhii** [Ecodev/graphql-doctrine#21]
All Models in my projects look like this
```php
use Popov\ZfcCore\Model\DomainAwareTrait;

class Marketplace
{
   use DomainAwareTrait;

      /**
     * @var int
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer", options={"unsigned":true})
     */
    private $id;
    // ...
}
```
and DomainAwareTrait looks like this
```php
namespace Popov\ZfcCore\Model;

use GraphQL\Doctrine\Annotation as API;

trait DomainAwareTrait
{
    /**
     * @API\Exclude
     *
     * @param array $data
     * @return $this
     */
    public function exchangeArray(array $data): self
    {
        foreach ($this->getArrayCopy() as $property => $value) {
            $this->{$property} = (isset($data[$property])) ? $data[$property] : $value;
        }

        return $this;
    }

    /**
     * @API\Exclude
     *
     * @return array
     */
    public function getArrayCopy(): array
    {
        return get_object_vars($this);
    }

    /**
     * @API\Exclude
     *
     * @return array
     */
    public function toArray(): array
    {
        return $this->getObjectAsArray();
    }
   // ...
}
```
Parts of these methods is required by framework (ZF) and other for custom purpouse.

But when I try implement simple Schema for my model I got Exception: `graphql-doctrine requires Popov\ZfcCore\Model\DomainAwareTrait entity to be configured with a Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver.`

This is my schema example:
```php
$schema = new Schema([
	'query' => new ObjectType([
		'name' => 'query',
		'fields' => [
			'marketplaces' => [
				'type' => Type::listOf($types->getOutput(Marketplace::class)), // Use automated ObjectType for output
				'args' => [
					[
						'name' => 'filter',
						'type' => $types->getFilter(Marketplace::class), // Use automated filtering options
					],
					[
						'name' => 'sorting',
						'type' => $types->getSorting(Marketplace::class), // Use automated sorting options
					],
				],
				'resolve' => function ($root, $args) use ($types) {
					$queryBuilder = $types->createFilteredQueryBuilder(Marketplace::class, $args['filter'] ?? [], $args['sorting'] ?? []);
					$result = $queryBuilder->getQuery()->getArrayResult();
					return $result;
				},
			],
		],
		'resolveField' => function($val, $args, $context, ResolveInfo $info) {
			return $this->{$info->fieldName}($val, $args, $context, $info);
		}
	])
]);
```
The exception is throwing only when 'filter' and 'sorting' are enabled.

**Comment by PowerKiKi** [comment]
It would seems like you are using a `\Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain`, as opposed to a simple `\Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver`. In that case you should define a default driver in that chain. So that we can use that default driver as a fallback to read trait's annotations.

Basically you want to go in that if:

https://github.com/Ecodev/graphql-doctrine/blob/ea111ae6bdee811e0a1918657e489b09e55398e8/src/Factory/MetadataReader/MappingDriverChainAdapter.php#L43-L48

Let me know if that helps

**Comment by PowerKiKi** [comment]
It would seems like you are using a `\Doctrine\Common\Persistence\Mapping\Driver\MappingDriverChain`, as opposed to a simple `\Doctrine\Common\Persistence\Mapping\Driver\AnnotationDriver`. In that case you should define a default driver in that chain. So that we can use that default driver as a fallback to read trait's annotations.

Basically you want to go in that if:

https://github.com/Ecodev/graphql-doctrine/blob/ea111ae6bdee811e0a1918657e489b09e55398e8/src/Factory/MetadataReader/MappingDriverChainAdapter.php#L43-L48

Let me know if that helps

**Comment by popovserhii** [comment]
Yes, you suggestion helped me but this is not obviously.
I thing it would be better if `AnnotationDriver` for Trait has taken from Model, such as Trait is subject of Model. Some projects can already have `defaultDriver` set to `YamlDriver` or `XmlDriver` and change this option can not be possible.

**Comment by PowerKiKi** [comment]
I agree with you. It would be best to use the model class, instead of the trait class.

However we don't use MappingDriverChain in our projects and I won't work on that feature. But if you are interested in it, feel free to submit a PR, covered by unit tests, then I would merge it.

**Comment by popovserhii** [comment]
Ok, I will try.
