### ISSUE TITLE
Properties starting with is/has IE: isActive instead of getActive

### ISSUE THREAD

**Issue by nkop** [Ecodev/graphql-doctrine#49]
Is there a reason all the getters must be named: getProperty().

We're wondering if there is a reason for this, since we think it's more logical to name a property active instead of IsActive.

This could be solved in the DefaultFieldResolver::getGetter() if desired.

**Comment by PowerKiKi** [comment]
Getters [must match](https://github.com/Ecodev/graphql-doctrine/blob/7111b7d26ef9a369c78604efcf568917fefca22a/src/Factory/OutputFieldsConfigurationFactory.php#L23) `~^(get|is|has)[A-Z]~` and setters [must match](https://github.com/Ecodev/graphql-doctrine/blob/7111b7d26ef9a369c78604efcf568917fefca22a/src/Factory/InputFieldsConfigurationFactory.php#L20) `~^set[A-Z]~`. Because we need a way to differentiate things that should be exposed through the API and other methods that should not be.

Knowing that, I suggest the following usage, because the prefix `is` naturally convey that the value is a boolean and nothing else:

```php
trait HasIsActive
{
    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" = 1})
     */
    private $isActive = true;

    /**
     * Set is active
     */
    public function setIsActive(bool $isActive): void
    {
        $this->isActive = $isActive;
    }

    /**
     * Get is active
     */
    public function isActive(): bool
    {
        return $this->isActive;
    }
}
```

which will generate something like:

```gql
type MyObject {
  """Is active"""
  isActive: Boolean!
}

input MyObjectInput {
  """Is active"""
  isActive: Boolean = true
}
```

Or this alternative, if you don't like `is`:

```php
trait HasActive
{
    /**
     * @var bool
     *
     * @ORM\Column(type="boolean", options={"default" = 1})
     */
    private $active = true;

    /**
     * Set is active
     */
    public function setActive(bool $active): void
    {
        $this->active = $active;
    }

    /**
     * Get is active
     */
    public function getActive(): bool
    {
        return $this->active;
    }
}
```
which would end up as:

```gql
type MyObject {
  """Is active"""
  active: Boolean!
}

input MyObjectInput {
  """Is active"""
  active: Boolean = true
}
```


So yes, that means that this library forces you to name things a certain way. And there is no (easy?) way around it. It was built this way to allow to quickly expose an API for a huge project, without refactoring the existing codebase.
